//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecept
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRecept()
        {
            this.tblComponents = new HashSet<tblComponent>();
        }
    
        public int ReceptID { get; set; }
        public int UserID { get; set; }
        public string ReceptName { get; set; }
        public string ReceptType { get; set; }
        public int PersonNumber { get; set; }
        public string Author { get; set; }
        public string ReceptText { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComponent> tblComponents { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
